# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b-audio-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listenAndSearchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.listenAndSearchBtn.setGeometry(QtCore.QRect(170, 60, 131, 23))
        self.listenAndSearchBtn.setObjectName("listenAndSearchBtn")
        self.addFingerprintsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addFingerprintsBtn.setGeometry(QtCore.QRect(190, 20, 101, 23))
        self.addFingerprintsBtn.setObjectName("addFingerprintsBtn")
        self.outputMessageLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputMessageLabel.setGeometry(QtCore.QRect(60, 100, 400, 50))
        self.outputMessageLabel.setAutoFillBackground(False)
        self.outputMessageLabel.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255)")
        self.outputMessageLabel.setText("")
        self.outputMessageLabel.setScaledContents(False)
        self.outputMessageLabel.setWordWrap(True)
        self.outputMessageLabel.setOpenExternalLinks(False)
        self.outputMessageLabel.setObjectName("outputMessageLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RCD - Audio Search"))
        self.listenAndSearchBtn.setText(_translate("MainWindow", "Listen and Recognize!"))
        self.addFingerprintsBtn.setText(_translate("MainWindow", "Add Fingerprints"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
