# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b-audio-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 200)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.selectSourceFolderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.selectSourceFolderBtn.setGeometry(QtCore.QRect(180, 40, 131, 23))
        self.selectSourceFolderBtn.setObjectName("selectSourceFolderBtn")
        self.addFingerprintsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.addFingerprintsBtn.setGeometry(QtCore.QRect(200, 80, 101, 23))
        self.addFingerprintsBtn.setObjectName("addFingerprintsBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.selectSourceFolderBtn.setText(_translate("MainWindow", "Select Source Folder"))
        self.addFingerprintsBtn.setText(_translate("MainWindow", "Add Fingerprints"))


if __name__ == "__main__":
    print("Should not run from here")
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # MainWindow = QtWidgets.QMainWindow()
    # ui = Ui_MainWindow()
    # ui.setupUi(MainWindow)
    # MainWindow.show()
    # sys.exit(app.exec_())
